# See environment variables in file ".env"
version: '3.8'
services:
  python:
    build:
      context: docker/python
      target: ${TARGET:-local} # dev or local
    shm_size: '2gb'
    environment:
      - MODELS_FOLDER=/opt/stable_diffusion/models/
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - .:/opt/stable_diffusion
      - ./models:/opt/stable-diffusion-webui/models
    networks:
      - app-tier
    ports:
      - 7860:7860
      - 8200:8200
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1450
  app-tier:
